import {useEffect,useState} from 'react';
import {parseModelSpec,serializeModelSpec} from '@velocut/provider-sdk/declarative';
import {modelCatalog,modelHostAvailable,modelHostCall,refreshModels,type ConnectionEntry} from '../services/declarative-models';
import {MODEL_TEMPLATES} from '../services/model-templates';
export function DeclarativeModels(){
 const [catalog,setCatalog]=useState(modelCatalog),[yaml,setYaml]=useState(''),[revision,setRevision]=useState<string|undefined>(),[connection,setConnection]=useState<Partial<ConnectionEntry>|null>(null),[token,setToken]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{const refresh=()=>setCatalog(modelCatalog());window.addEventListener('velocut-models-changed',refresh);return()=>window.removeEventListener('velocut-models-changed',refresh);},[]);
 const perform=async(work:()=>Promise<void>)=>{setBusy(true);setError('');setNotice('');try{await work();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}};
 const exportYaml=()=>{const url=URL.createObjectURL(new Blob([yaml],{type:'application/yaml'})),a=document.createElement('a');a.href=url;a.download='velocut-model.yaml';a.click();URL.revokeObjectURL(url);};
 return <section className="model-settings declarative-models"><h3>Model definitions</h3><p>Import a model configuration or ask Codex to create one from API documentation. No packages or source changes are needed.</p>
 {!modelHostAvailable()&&<p>Start this editor with the current Velocut Studio CLI to enable local model configuration.</p>}
 {catalog.models.map(m=><div className="model-channel" key={m.id}><div><strong>{m.spec.label??m.id}</strong><small>{m.spec.capability} · {m.spec.execution.type}</small></div><button onClick={()=>{setYaml(serializeModelSpec(m.spec));setRevision(m.revision);}}>Edit definition</button><button onClick={()=>{setConnection({id:m.id+'-connection',modelId:m.id,baseUrl:''});setToken('');}}>Connect</button><button onClick={()=>void perform(async()=>{await modelHostCall({action:'remove',id:m.id,expectedRevision:m.revision});await refreshModels();})}>Remove model</button></div>)}
 <div className="dialog-actions"><button disabled={busy} onClick={()=>void perform(async()=>{await refreshModels();setNotice('Model list refreshed.');})}>Refresh models</button><label>Start from a template<select aria-label="Model definition template" value="" onChange={e=>{const item=MODEL_TEMPLATES.find(x=>x.id===e.target.value);if(item){setYaml(serializeModelSpec(item));setRevision(undefined);}}}><option value="">Choose a template</option>{MODEL_TEMPLATES.map(m=><option key={m.id} value={m.id}>{m.label??m.id}</option>)}</select></label><label className="button">Import YAML<input aria-label="Import model YAML" type="file" accept=".yaml,.yml,.json" onChange={e=>{const file=e.target.files?.[0];if(file)void perform(async()=>{setYaml(await file.text());setRevision(undefined);});}}/></label><button onClick={()=>{setYaml(serializeModelSpec(MODEL_TEMPLATES[0]));setRevision(undefined);}}>New definition</button></div>
 {yaml&&<><label>Model YAML<textarea aria-label="Model YAML" rows={12} spellCheck={false} value={yaml} onChange={e=>setYaml(e.target.value)}/></label><div className="dialog-actions"><button disabled={busy} onClick={()=>void perform(async()=>{await modelHostCall({action:'validate',definition:yaml});setNotice('Definition valid. No service request sent.');})}>Validate definition</button><button disabled={busy} className="primary" onClick={()=>void perform(async()=>{const saved=await modelHostCall({action:'upsert',definition:yaml,...(revision?{expectedRevision:revision}:{})});setRevision(saved.revision);await refreshModels();setNotice('Model definition saved.');})}>Save definition</button><button onClick={()=>{try{parseModelSpec(yaml);exportYaml();}catch(e){setError(String(e));}}}>Export YAML</button><button onClick={()=>setYaml('')}>Close definition</button></div></>}
 {catalog.connections.map(c=><div className="model-channel" key={c.id}><div><strong>{c.label??c.id}</strong><small>{c.modelId} · {c.credentialConfigured?'Credential saved':'No credential'}</small></div><button onClick={()=>{setConnection(c);setToken('');}}>Edit connection</button><button onClick={()=>void perform(async()=>{await modelHostCall({action:'connections',id:c.id});await refreshModels();})}>Remove connection</button></div>)}
 {connection&&<fieldset><legend>Model connection</legend><label>Connection name<input aria-label="Declarative connection name" value={connection.id??''} disabled={!!connection.revision} onChange={e=>setConnection({...connection,id:e.target.value})}/></label><label>Base URL<input aria-label="Declarative Base URL" value={connection.baseUrl??''} onChange={e=>setConnection({...connection,baseUrl:e.target.value})}/></label><label>Remote model ID<input aria-label="Declarative remote model" value={connection.remoteModel??''} onChange={e=>setConnection({...connection,remoteModel:e.target.value})}/></label><label>API Token<input aria-label="Declarative API Token" type="password" autoComplete="off" value={token} placeholder="Stored locally; never returned to Codex" onChange={e=>setToken(e.target.value)}/></label><div className="dialog-actions"><button disabled={busy} onClick={()=>void perform(async()=>{const {id,modelId,baseUrl,remoteModel,label}=connection;await modelHostCall({action:'connections',connection:{id,modelId,baseUrl,remoteModel,label},...(connection.revision?{expectedRevision:connection.revision}:{})});if(token)await modelHostCall({action:'setCredential',id,token});await refreshModels();setConnection(null);setToken('');setNotice('Connection saved.');})}>Save connection</button><button onClick={()=>{setConnection(null);setToken('');}}>Cancel connection</button></div></fieldset>}
 {error&&<p role="alert" className="scene-error">{error}</p>}{notice&&<p role="status">{notice}</p>}
 </section>;
}
