import {useEffect,useState} from 'react';
import type {ParameterField,ParameterValue,ModelSettings as Settings} from '@velocut/provider-sdk/catalog';
import {allModelChannels,saveModelChannels,validateChannel,modelProtocols,MODEL_PRESETS,modelPreset,parameterDefaults,parameterFields,type ModelChannel} from '../services/model-config';
import {parseVideoCapabilities} from '../services/videogen';
export function ParameterFields({fields,values,onChange,disabled=false,prefix='Parameter'}:{fields:ParameterField[];values:Record<string,ParameterValue>;onChange:(v:Record<string,ParameterValue>)=>void;disabled?:boolean;prefix?:string}){
 const set=(key:string,value:ParameterValue|undefined)=>{const next={...values};if(value===undefined)delete next[key];else next[key]=value;onChange(next);};
 return <div className="generation-range">{fields.map(f=><label key={f.key}>{f.label}{f.required?' *':''}{f.type==='select'?<select aria-label={`${prefix} ${f.label}`} disabled={disabled} value={values[f.key]===undefined?'':JSON.stringify(values[f.key])} onChange={e=>set(f.key,e.target.value?JSON.parse(e.target.value):undefined)}><option value="">Model / provider default</option>{f.options?.map(v=><option key={JSON.stringify(v)} value={JSON.stringify(v)}>{String(v)}</option>)}</select>:f.type==='boolean'?<select aria-label={`${prefix} ${f.label}`} disabled={disabled} value={values[f.key]===undefined?'':String(values[f.key])} onChange={e=>set(f.key,e.target.value===''?undefined:e.target.value==='true')}><option value="">Model / provider default</option><option value="true">On</option><option value="false">Off</option></select>:<input aria-label={`${prefix} ${f.label}`} disabled={disabled} type={f.type==='number'?'number':'text'} min={f.min} max={f.max} step={f.integer?1:'any'} value={String(values[f.key]??'')} onChange={e=>set(f.key,e.target.value===''?undefined:f.type==='number'?Number(e.target.value):e.target.value)}/>}</label>)}</div>;
}
export function ModelSettings({videoOnly=false}:{videoOnly?:boolean}){
 const [channels,setChannels]=useState(allModelChannels),[draft,setDraft]=useState<ModelChannel|null>(null),[editing,setEditing]=useState<string|null>(null),[active,setActive]=useState(''),[token,setToken]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[parameterJson,setParameterJson]=useState('[]'),[capJson,setCapJson]=useState('{}');
 useEffect(()=>{const refresh=()=>setChannels(allModelChannels());window.addEventListener('velocut-models-changed',refresh);window.addEventListener('storage',refresh);return()=>{window.removeEventListener('velocut-models-changed',refresh);window.removeEventListener('storage',refresh);};},[]);
 const kinds=modelProtocols().filter(p=>!videoOnly||p.kind==='video');
 const close=()=>{setDraft(null);setEditing(null);setToken('');setError('');setNotice('');};
 const open=(c:ModelChannel|null)=>{const value=c??{id:'channel-'+crypto.randomUUID().slice(0,8),kind:'task-api',baseUrl:'',apiKey:'',models:[]};setDraft(structuredClone(value));setEditing(c?.id??null);setActive(c?.defaultModel??c?.models[0]??'');setToken('');setError('');setNotice('');setCapJson(JSON.stringify(c?.capabilities??{},null,2));setParameterJson(JSON.stringify(c?.modelSettings?.[c?.defaultModel??c?.models[0]??'']?.parameters??[],null,2));};
 const selected=draft?.modelSettings?.[active]??{},preset=modelPreset(selected.presetId);
 const updateSettings=(settings:Settings)=>{if(draft&&active)setDraft({...draft,modelSettings:{...draft.modelSettings,[active]:settings}});};
 const selectModel=(model:string)=>{setActive(model);setParameterJson(JSON.stringify(draft?.modelSettings?.[model]?.parameters??[],null,2));};
 const defaults=parameterDefaults(selected);
 const baseFields:ParameterField[]=draft&&kinds.find(p=>p.id===draft.kind)?.kind==='video'?[...(draft.kind==='minimax-video'?[]:[{key:'ratio',label:'Aspect ratio',type:(preset?.capabilities?.ratios?'select':'text') as 'select'|'text',options:preset?.capabilities?.ratios}]),{key:'resolution',label:'Resolution',type:preset?.capabilities?.resolutions?'select':'text',options:preset?.capabilities?.resolutions},...(draft.kind==='minimax-video'?[]:[{key:'generateAudio',label:'Generate audio',type:'boolean' as const}])]:[];
 const parsed=()=>{if(!draft)throw Error('Choose a channel');const parameters=JSON.parse(parameterJson);const next={...draft,id:draft.id.trim(),baseUrl:draft.baseUrl.trim().replace(/\/+$/,''),apiKey:token.trim()||draft.apiKey,models:draft.models.map(m=>m.trim()).filter(Boolean),capabilities:parseVideoCapabilities(JSON.parse(capJson)),modelSettings:{...draft.modelSettings,...(active?{[active]:{...selected,parameters}}:{})}};next.defaultModel=next.models.includes(next.defaultModel?.trim()??'')?next.defaultModel!.trim():next.models[0];next.modelSettings=Object.fromEntries(Object.entries(next.modelSettings).map(([key,value])=>[key.trim(),value]).filter(([key])=>next.models.includes(key as string)));if(next.models.length!==new Set(next.models).size)throw Error('Duplicate model IDs');if(channels.some(c=>c.id===next.id&&c.id!==editing))throw Error('Channel name already exists');validateChannel(next);return next;};
 if(!draft)return <section className="videogen-settings model-settings"><h4>Media model channels</h4><p>Choose the service protocol and model, then provide your own Base URL and API Token. Presets configure model parameters; they do not provide an account.</p>{channels.filter(c=>!videoOnly||!['minimax-speech','minimax-music'].includes(c.kind)).map(c=><div className="model-channel" key={c.id}><div><strong>{c.label??c.id}</strong><small>{modelProtocols().find(p=>p.id===c.kind)?.label??c.kind} · {c.models.join(', ')}</small></div><button onClick={()=>open(c)}>Edit</button><button aria-label={`Remove channel ${c.id}`} onClick={()=>{saveModelChannels(channels.filter(x=>x.id!==c.id));}}>Remove</button></div>)}<button onClick={()=>open(null)}>+ Add channel</button></section>;
 return <section className="videogen-settings model-settings"><h4>{editing?'Edit model channel':'Add model channel'}</h4>
 <label>Model preset<select aria-label="Model preset" value={selected.presetId??''} onChange={e=>{const p=modelPreset(e.target.value);if(!p){updateSettings({...selected,presetId:undefined});return;}const model=p.model||active;setDraft({...draft,kind:p.protocol,baseUrl:draft.baseUrl||p.baseUrl||'',models:model?[model]:[],defaultModel:model||undefined,modelSettings:{[model]:{presetId:p.id}}});setActive(model);setParameterJson('[]');setCapJson('{}');}}><option value="">Custom model</option>{MODEL_PRESETS.filter(p=>!videoOnly||p.kind==='video').map(p=><option key={p.id} value={p.id}>{p.label}</option>)}</select></label>
 <div className="generation-range"><label>Channel name<input aria-label="Channel name" value={draft.id} onChange={e=>setDraft({...draft,id:e.target.value})}/></label><label>API protocol<select aria-label="Model protocol" value={draft.kind} onChange={e=>{setDraft({...draft,kind:e.target.value,modelSettings:{},capabilities:{}});setParameterJson('[]');setCapJson('{}');}}>{kinds.map(p=><option key={p.id} value={p.id}>{p.label}</option>)}</select></label></div>
 <label>Base URL<input aria-label="Model Base URL" type="url" value={draft.baseUrl} placeholder="https://your-service.example" onChange={e=>setDraft({...draft,baseUrl:e.target.value})}/></label>
 {import.meta.env.DEV&&<button onClick={()=>{try{const url=new URL(draft.baseUrl);if(url.protocol!=='https:')throw Error('The development relay accepts HTTPS upstreams');setDraft({...draft,baseUrl:`${location.origin}/videogen-proxy/${url.host}${url.pathname.replace(/\/+$/,'')}`});setError('');}catch(e){setError(String(e instanceof Error?e.message:e));}}}>Use local development relay</button>}
 <label>API Token<input aria-label="Model API Token" type="password" autoComplete="off" value={token} placeholder={draft.apiKey?'Saved — leave blank to keep':'Token issued by this service'} onChange={e=>setToken(e.target.value)}/></label>
 <label>Model IDs<input aria-label="Model IDs" placeholder="Model or deployment ID; separate multiple IDs with commas" value={draft.models.join(',')} onChange={e=>{const models=e.target.value.split(',');const settings=Object.fromEntries(models.filter(Boolean).map(model=>[model,draft.modelSettings?.[model]??selected]));setDraft({...draft,models,defaultModel:models[0]||undefined,modelSettings:settings});setActive(models.includes(active)?active:models[0]);}}/></label>
 {draft.models.filter(Boolean).length>1&&<label>Configure model<select aria-label="Configure model" value={active} onChange={e=>selectModel(e.target.value)}>{draft.models.filter(Boolean).map(m=><option key={m}>{m}</option>)}</select></label>}
 {active&&<><p className="empty-hint">Default parameters for {active}. Each generation can override these values.</p><ParameterFields prefix="Default" fields={[...baseFields,...parameterFields(selected)]} values={defaults} onChange={values=>updateSettings({...selected,defaults:values})}/></>}
 <details><summary>Advanced model parameters</summary><p className="empty-hint">Optional scalar controls for compatible gateways: key, label, type, options, min/max, default. URLs, tokens and reference inputs use their dedicated controls.</p><textarea aria-label="Custom parameter definitions" rows={4} value={parameterJson} onChange={e=>setParameterJson(e.target.value)}/><label>Video capability overrides<textarea aria-label="Model capabilities JSON" rows={3} value={capJson} onChange={e=>setCapJson(e.target.value)}/></label></details>
 <p className="empty-hint">Configuration checks are local and spend no credits. The service must support this protocol and allow browser CORS, or be reached through your compatible proxy.</p>
 <div className="dialog-actions"><button onClick={()=>{try{parsed();setError('');setNotice('Configuration valid. No API request sent; credentials are checked by the service during generation.');}catch(e){setError(String(e instanceof Error?e.message:e));}}}>Check configuration</button><button className="primary" onClick={()=>{try{const next=parsed();saveModelChannels(editing?channels.map(c=>c.id===editing?next:c):[...channels,next]);close();}catch(e){setError(String(e instanceof Error?e.message:e));}}}>{editing?'Save channel':'Add channel'}</button><button onClick={close}>Cancel</button></div>
 {error&&<p className="scene-error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 </section>;
}
