import {ProviderError,type ProviderDefinition,type JsonObject} from '@velocut/provider-sdk';
import {validateVideoModel,type ModelSettings} from '@velocut/provider-sdk/catalog';
export const arkVideoProvider:ProviderDefinition={apiVersion:1,id:'ark-video',label:'Ark / Seedance content tasks',capabilities:['video.generate'],credentials:[{name:'apiKey',required:true}],configSchema:{type:'object',required:['baseUrl'],properties:{baseUrl:{type:'string'},modelSettings:{type:'object'}}},create(context){
 if(typeof context.config.baseUrl!=='string')throw Error('Base URL is required');const u=new URL(context.config.baseUrl);if(!['https:','http:'].includes(u.protocol)||u.username||u.password||u.search||u.hash)throw Error('Invalid Base URL');const base=context.config.baseUrl.replace(/\/+$/,''),settings=context.config.modelSettings as unknown as ModelSettings|undefined;
 const json=async(path:string,signal?:AbortSignal,body?:JsonObject)=>{const token=await context.credentials.get('apiKey');signal?.throwIfAborted();const response=await context.fetch(base+path,{method:body?'POST':'GET',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{}),signal});const data=await response.json().catch(()=>({})) as any;if(!response.ok)throw new ProviderError({phase:body?'submit':'poll',code:data.error?.code??'ARK_HTTP',message:data.error?.message??`Ark HTTP ${response.status}`,httpStatus:response.status,outcome:response.status>=500?'unknown':'rejected',retryable:response.status>=500||response.status===429});return data;};
 return {models:()=>[],supports:r=>{try{if(r.capability!=='video.generate'||typeof r.input.prompt!=='string'||!r.input.prompt.trim())throw Error('Video prompt is required');if(Object.keys(r.input).some(k=>!['prompt','durationS','ratio','resolution','generateAudio','parameters','firstFrameReferenceId','lastFrameReferenceId','referenceImageIds','referenceVideoIds','referenceAudioIds'].includes(k)))throw Error('Unsupported Ark input');validateVideoModel(settings,r.input);return {supported:true};}catch(e){return {supported:false,reason:String(e instanceof Error?e.message:e)};}},
 async submit(r,call){const i=r.input,content:JsonObject[]=[{type:'text',text:i.prompt}];for(const [name,kind,role,multiple] of [['firstFrameReferenceId','image','first_frame',false],['lastFrameReferenceId','image','last_frame',false],['referenceImageIds','image','reference_image',true],['referenceVideoIds','video','reference_video',true],['referenceAudioIds','audio','reference_audio',true]] as const){if(i[name]===undefined)continue;if(!call.resources)throw Error('Reference transport is required');for(const id of multiple?i[name] as string[]:[i[name] as string]){const url=await call.resources.urlFor(id,kind);content.push({type:kind+'_url',[kind+'_url']:{url},role});}}
 const body:JsonObject={model:r.model,content,...(i.parameters as JsonObject??{})};for(const [name,to] of [['durationS','duration'],['resolution','resolution'],['ratio','ratio'],['generateAudio','generate_audio']])if(i[name]!==undefined)body[to]=i[name];const result=await json('/contents/generations/tasks',call.signal,body);return {id:result.id};},
 async poll(receipt,call){const data=await json(`/contents/generations/tasks/${encodeURIComponent(receipt.id)}`,call.signal);if(data.status==='succeeded'){if(typeof data.content?.video_url!=='string')throw Error('Completed task has no video URL');return {state:'succeeded',result:{outputs:[{kind:'video',source:{kind:'url',url:data.content.video_url}}]}};}if(['failed','cancelled','expired'].includes(data.status))return {state:'failed',error:{phase:'poll',code:data.error?.code??'ARK_FAILED',message:data.error?.message??'Video generation failed',outcome:'rejected',retryable:false}};if(!['queued','running'].includes(data.status))throw new ProviderError({phase:'poll',code:'UNKNOWN_STATUS',message:'Unknown Ark task status',outcome:'unknown',retryable:false});return {state:'running',status:data.status};},
 };
}};
