import {test,expect} from '@playwright/test';
import {mkdtemp,rm} from 'node:fs/promises';
import {readFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {Client} from '@modelcontextprotocol/client';
import {StdioClientTransport} from '@modelcontextprotocol/client/stdio';
import {createModelHost} from '../packages/cli/src/models.mjs';

test('Codex configures an unknown model, nested input reaches HTTP, and a pinned task survives YAML edits and reload',async({page},info)=>{
 const directory=await mkdtemp(join(tmpdir(),'velocut-declarative-e2e-'));let ready=false;const calls:any[]=[];
 const host=createModelHost({directory,fetch:async(url:string,init:any)=>{calls.push({url,body:init.body?JSON.parse(init.body):undefined});return Response.json(init.method==='POST'?{job:'one'}:ready?{state:'done',file:'http://localhost:5173/__declared.mp4'}:{state:'waiting'});}});
 await page.route('**/__velocut/models',async route=>{try{const data=await host.execute(route.request().postDataJSON());await route.fulfill({json:{ok:true,data}});}catch(e){await route.fulfill({status:400,json:{ok:false,error:String((e as Error).message)}});}});
 await page.route('**/__velocut/models/download/*',route=>route.fulfill({contentType:'video/mp4',body:readFileSync(resolve('e2e/fixtures/red-tone.mp4'))}));
 await page.route('**/__declared.mp4',route=>route.fulfill({contentType:'video/mp4',body:readFileSync(resolve('e2e/fixtures/red-tone.mp4'))}));
 const client=new Client({name:'declarative-model-test',version:'1'});await client.connect(new StdioClientTransport({command:process.execPath,args:[resolve('packages/mcp/dist/velocut/scripts/server.cjs')],stderr:'pipe'}));
 const tool=async(name:string,args:Record<string,unknown>={})=>(await client.callTool({name,arguments:args}) as any).structuredContent;
 try{
   await page.setViewportSize({width:400,height:800});await page.goto((await tool('velocut_connect')).url);await expect(page.locator('.codex-status')).toHaveClass(/\bconnected\b/);const sessionId=(await tool('velocut_sessions')).sessions[0].sessionId;
   const definition={version:1,id:'a-model-velocut-has-never-seen',label:'My custom model',capability:'video.generate',timeline:{prompt:'description',duration:'seconds'},inputSchema:{type:'object',required:['description','seconds'],additionalProperties:false,properties:{description:{type:'string'},seconds:{type:'integer',enum:[1,2]},camera:{type:'object',properties:{speed:{type:'number',default:.4},moves:{type:'array',items:{type:'string'}}}}}},execution:{type:'async-http',submit:{method:'POST',path:'/create',body:{$input:''}},receipt:{id:'$.job'},poll:{method:'GET',path:'/status/{receipt.id}',status:'$.state',states:{running:['waiting'],succeeded:['done'],failed:['error']}},outputs:[{kind:'video',url:'$.file'}]}};
   const saved=await tool('velocut_models',{sessionId,action:'upsert',definition});expect(saved.ok,JSON.stringify(saved)).toBe(true);
   const configured=await tool('velocut_models',{sessionId,action:'connections',connection:{id:'custom-connection',modelId:definition.id,baseUrl:'https://provider.invalid'}});expect(configured.ok,JSON.stringify(configured)).toBe(true);expect(calls).toHaveLength(0);
   await page.getByRole('button',{name:'Model settings',exact:true}).click();await page.getByRole('button',{name:'Edit connection',exact:true}).click();await page.getByLabel('Declarative API Token').fill('private-do-not-disclose');await page.getByRole('button',{name:'Save connection',exact:true}).click();await expect(page.getByRole('status')).toContainText('Connection saved');await page.screenshot({path:info.outputPath('declarative-models.png')});await page.getByRole('button',{name:'Close Media models',exact:true}).click();
   const listed=await tool('velocut_models',{sessionId,action:'list'});expect(JSON.stringify(listed)).not.toContain('private-do-not-disclose');
   const preview=await tool('velocut_models',{sessionId,action:'preview',connectionId:'custom-connection',input:{description:'Lake',seconds:1,camera:{moves:['pan','tilt']}}});expect(preview.ok,JSON.stringify(preview)).toBe(true);expect(preview.request.body.camera).toEqual({speed:.4,moves:['pan','tilt']});expect(calls).toHaveLength(0);
   await page.getByRole('button',{name:'Draw generation range',exact:true}).click();await page.getByRole('button',{name:'Set range…',exact:true}).click();await page.getByLabel('Generation duration',{exact:true}).fill('1');await page.getByLabel('Input description',{exact:true}).fill('A lake');await page.getByLabel('Input seconds',{exact:true}).selectOption('1');await page.getByLabel('Input camera speed',{exact:true}).fill('0.8');await page.getByLabel('Input camera moves',{exact:true}).fill('["pan","tilt"]');await page.getByRole('button',{name:'Generate video',exact:true}).click();
   await expect.poll(()=>calls.filter(c=>c.body).length).toBe(1);expect(calls[0].body).toEqual({description:'A lake',seconds:1,camera:{speed:.8,moves:['pan','tilt']}});
   await expect.poll(()=>calls.filter(c=>!c.body).length).toBeGreaterThan(0);
   const changed=structuredClone(definition);changed.execution.poll.path='/different/{receipt.id}';const update=await tool('velocut_models',{sessionId,action:'upsert',definition:changed,expectedRevision:saved.revision});expect(update.ok,JSON.stringify(update)).toBe(true);
   await page.reload();await page.waitForFunction(()=>(window as any).velocut?.generation);ready=true;
   await expect.poll(async()=>{const r=await page.evaluate(()=>(window as any).velocut.generation({action:'list'}));return r.items[0]?.state;},{timeout:20000}).toBe('succeeded');expect(calls.filter(c=>c.body)).toHaveLength(1);expect(calls.filter(c=>!c.body).every(c=>c.url.includes('/status/'))).toBe(true);
   const doc=await page.evaluate(()=>(window as any).velocut.doc());expect(doc.generationSlots[0].request.input.camera.moves).toEqual(['pan','tilt']);
 }finally{await client.close();await rm(directory,{recursive:true,force:true});}
});

test('YAML import configures a synchronous audio model and generates from its nested schema',async({page})=>{
 const directory=await mkdtemp(join(tmpdir(),'velocut-audio-definition-'));let body:any;
 const wav=Buffer.alloc(44+1600);wav.write('RIFF');wav.writeUInt32LE(wav.length-8,4);wav.write('WAVEfmt ',8);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(8000,24);wav.writeUInt32LE(16000,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(1600,40);
 const host=createModelHost({directory,fetch:async(_url:string,init:any)=>{body=JSON.parse(init.body);return Response.json({data:{audio:wav.toString('hex')},base_resp:{status_code:0}});}});
 await page.route('**/__velocut/models',async route=>{try{const data=await host.execute(route.request().postDataJSON());await route.fulfill({contentType:'application/json',body:JSON.stringify({ok:true,data},(_k,v)=>v instanceof Uint8Array?{$bytes:Buffer.from(v).toString('base64')}:v)});}catch(e){await route.fulfill({status:400,json:{ok:false,error:(e as Error).message}});}});
 try{
 await page.goto('/');await page.waitForFunction(()=>(window as any).velocut?.modelConfiguration);await page.getByRole('button',{name:'Model settings',exact:true}).click();await page.getByLabel('Model definition template').selectOption('minimax-speech');await page.getByRole('button',{name:'Validate definition',exact:true}).click();await expect(page.getByRole('status')).toContainText('No service request');expect(body).toBeUndefined();await page.getByRole('button',{name:'Save definition',exact:true}).click();await expect(page.getByRole('status')).toContainText('saved');await page.getByRole('button',{name:'Connect',exact:true}).click();await page.getByLabel('Declarative Base URL').fill('https://audio.invalid');await page.getByLabel('Declarative remote model').fill('custom-speech-id');await page.getByLabel('Declarative API Token').fill('audio-token');await page.getByRole('button',{name:'Save connection',exact:true}).click();await expect(page.getByRole('status')).toContainText('Connection saved');await page.getByLabel('Audio channel',{exact:true}).selectOption('minimax-speech-connection');await page.getByLabel('Audio input text',{exact:true}).fill('Hello');await page.getByLabel('Audio input voice_setting voice_id',{exact:true}).fill('user-voice');await page.getByLabel('Audio input voice_setting speed',{exact:true}).fill('1.2');await page.getByRole('button',{name:'Generate audio',exact:true}).click();await expect(page.locator('audio')).toBeVisible();expect(body.model).toBe('custom-speech-id');expect(body.voice_setting).toEqual({voice_id:'user-voice',speed:1.2});await page.getByRole('button',{name:'Keep audio in assets',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).velocut.doc().assets.filter((a:any)=>a.kind==='audio').length)).toBe(1);
 }finally{await rm(directory,{recursive:true,force:true});}
});
