import {test,expect,type Page} from './test-fixtures';import {readFileSync} from 'node:fs';import {resolve} from 'node:path';
async function addModel(page:Page,preset:string,id:string,base:string){
 await page.getByRole('button',{name:'Model settings',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Media models',exact:true});await dialog.getByRole('button',{name:'+ Add channel',exact:true}).click();await dialog.getByLabel('Model preset',{exact:true}).selectOption(preset);await dialog.getByLabel('Channel name',{exact:true}).fill(id);await dialog.getByLabel('Model Base URL',{exact:true}).fill(base);await dialog.getByLabel('Model API Token',{exact:true}).fill('user-token-fixture');return dialog;
}
test('Base URL and token configuration creates an H3 video channel and drives the timeline with preset parameters',async({page},testInfo)=>{
 let posts=0,body:any;await page.setViewportSize({width:400,height:780});await page.route('**/__gateway/api/v1/tasks**',async route=>{if(route.request().method()==='POST'){posts++;body=route.request().postDataJSON();expect(route.request().headers().authorization).toBe('Bearer user-token-fixture');await route.fulfill({json:{data:{id:'configured-video'}}});}else await route.fulfill({json:{data:{status:'completed',result:{url:new URL('/__video.mp4',route.request().url()).href}}}});});
 await page.route('**/__video.mp4',route=>route.fulfill({contentType:'video/mp4',body:readFileSync(resolve('e2e/fixtures/red-tone.mp4'))}));
 await page.goto('/');await page.waitForFunction(()=>(window as any).velocut?.generation);const dialog=await addModel(page,'minimax-h3','my-h3',new URL('/__gateway',page.url()).href);await expect(dialog.getByLabel('Model IDs',{exact:true})).toHaveValue('minimax-h3');await expect(dialog.getByLabel('Default Resolution',{exact:true})).toHaveValue('"2K"');
 await dialog.getByRole('button',{name:'Check configuration',exact:true}).click();await expect(dialog.getByRole('status')).toContainText('No API request sent');expect(posts).toBe(0);await dialog.getByRole('button',{name:'Add channel',exact:true}).click();await page.screenshot({path:testInfo.outputPath('model-settings.png')});await page.getByRole('button',{name:'Close Media models',exact:true}).click();await page.reload();await page.waitForFunction(()=>(window as any).velocut?.generation);
 await page.getByRole('button',{name:'Draw generation range',exact:true}).click();await page.getByRole('button',{name:'Set range…',exact:true}).click();await page.getByLabel('Generation duration',{exact:true}).fill('1');await page.getByLabel('Video generation prompt').fill('A quiet landscape');await page.getByRole('button',{name:'Generate video',exact:true}).click();await expect(page.getByRole('dialog',{name:'Generate video',exact:true}).getByText('Ready',{exact:true})).toBeVisible();
 expect(body).toEqual({model:'minimax-h3',params:{prompt:'A quiet landscape',duration:4,ratio:'adaptive',resolution:'2K',generate_audio:false}});expect(posts).toBe(1);const discovered=await page.evaluate(()=>(window as any).velocut.generation({action:'capabilities'}));expect(JSON.stringify(discovered)).not.toContain('user-token-fixture');expect(discovered.channels[0].modelSettings['minimax-h3'].presetId).toBe('minimax-h3');
});
test('custom scalar model parameters survive project reload and reach the gateway without code registration',async({page})=>{
 let body:any;await page.route('**/__custom/api/v1/tasks**',async route=>{if(route.request().method()==='POST'){body=route.request().postDataJSON();await route.fulfill({json:{task_id:'one'}});}else await route.fulfill({json:{status:'processing'}});});
 await page.goto('/');await page.waitForFunction(()=>(window as any).velocut?.generation);const dialog=await addModel(page,'task-generic','custom',new URL('/__custom',page.url()).href);await dialog.getByLabel('Model IDs',{exact:true}).fill('my-private-video');await dialog.getByText('Advanced model parameters',{exact:true}).click();await dialog.getByLabel('Custom parameter definitions').fill(JSON.stringify([{key:'seed',label:'Seed',type:'number',integer:true,min:0,default:42},{key:'negative_prompt',label:'Negative prompt',type:'text',default:'blur'}]));await dialog.getByRole('button',{name:'Add channel',exact:true}).click();await page.getByRole('button',{name:'Close Media models',exact:true}).click();
 const submitted=await page.evaluate(async()=>{const v=(window as any).velocut;await v.apply({type:'addTrack',kind:'video'});await v.apply({type:'addGenerationSlot',trackId:'track_1',startUs:0,durationUs:1e6,request:{channel:'custom',model:'my-private-video',prompt:'Scene',parameters:{seed:43}}});return v.generation({action:'submit',slotId:'slot_2',intentVersion:1,requestId:'custom'});});expect(submitted.ok,JSON.stringify(submitted)).toBe(true);await expect.poll(()=>body).toBeTruthy();expect(body.params.seed).toBe(43);expect(body.params.negative_prompt).toBe('blur');
 await page.reload();await page.waitForFunction(()=>(window as any).velocut?.generation);const request=await page.evaluate(()=>(window as any).velocut.doc().generationSlots[0].request);expect(request.parameters.seed).toBe(43);const caps=await page.evaluate(()=>(window as any).velocut.generation({action:'capabilities'}));expect(caps.channels[0].modelSettings['my-private-video'].parameters).toHaveLength(2);
});
function audioHex(){const wav=Buffer.alloc(44+1600);wav.write('RIFF');wav.writeUInt32LE(wav.length-8,4);wav.write('WAVEfmt ',8);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(8000,24);wav.writeUInt32LE(16000,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(1600,40);return wav.toString('hex');}
test('speech can be configured, previewed, recovered after reload and kept as an audio asset',async({page})=>{
 let posts=0,body:any;await page.route('**/__mini/v1/t2a_v2',async route=>{posts++;body=route.request().postDataJSON();await route.fulfill({json:{base_resp:{status_code:0},data:{audio:audioHex()}}});});
 await page.goto('/');await page.waitForFunction(()=>(window as any).velocut?.generation);const dialog=await addModel(page,'speech-2.8-hd','my-speech',new URL('/__mini/v1',page.url()).href);await dialog.getByLabel('Default Voice ID',{exact:true}).fill('voice-user');await dialog.getByLabel('Default Speaking speed',{exact:true}).fill('1.2');await dialog.getByRole('button',{name:'Add channel',exact:true}).click();await dialog.getByLabel('Audio channel',{exact:true}).selectOption('my-speech');await dialog.getByLabel('Audio prompt').fill('Hello');await dialog.getByRole('button',{name:'Generate audio',exact:true}).click();await expect(dialog.locator('audio')).toBeVisible();expect(body.voice_setting).toMatchObject({voice_id:'voice-user',speed:1.2});expect(posts).toBe(1);
 await page.reload();await page.waitForFunction(()=>(window as any).velocut?.generation);await page.getByRole('button',{name:'Model settings',exact:true}).click();await page.getByText('Audio generation history',{exact:true}).click();await page.getByRole('button',{name:'Preview saved audio',exact:true}).click();await expect(page.getByRole('dialog',{name:'Media models'}).locator('audio')).toBeVisible();await page.getByRole('button',{name:'Keep audio in assets',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).velocut.doc().assets.filter((a:any)=>a.kind==='audio').length)).toBe(1);expect(posts).toBe(1);
});
test('music uses lyrics and the configured music endpoint',async({page})=>{
 let body:any;await page.route('**/__music/v1/music_generation',async route=>{body=route.request().postDataJSON();await route.fulfill({json:{data:{audio:audioHex()}}});});await page.goto('/');await page.waitForFunction(()=>(window as any).velocut?.generation);const dialog=await addModel(page,'music-2.5','music',new URL('/__music',page.url()).href);await dialog.getByRole('button',{name:'Add channel',exact:true}).click();await dialog.getByLabel('Audio channel',{exact:true}).selectOption('music');await dialog.getByLabel('Audio prompt').fill('Jazz');await dialog.getByLabel('Song lyrics').fill('[Verse] Hello');await dialog.getByRole('button',{name:'Generate audio',exact:true}).click();await expect(dialog.locator('audio')).toBeVisible();expect(body.model).toBe('music-2.5');expect(body.lyrics).toBe('[Verse] Hello');expect(body.audio_setting.sample_rate).toBe(44100);
});
