// prompt.ts — render the asset manifest into the agent-facing vocabulary.
//
// This is what grounds the agent: it can only name models, clips and
// environments that actually exist, and locomotion clips advertise their
// natural gait speed so position keyframes can be paced to match (no
// skating). Served to programs via the sceneAssets() script RPC, so the
// vocabulary always reflects the shipped manifest — no prompt edits when
// assets are added.

import { MANNEQUIN_JOINTS, POSE_PRESETS } from './mannequin.ts';
import type { SceneAssetManifest } from './types.ts';
import { SCENE_LIMITS } from './geometry.ts';

export function scenePromptDoc(manifest: SceneAssetManifest): string {
  const lines: string[] = [];
  lines.push('Characters (model id → animation clips):');
  for (const [id, c] of Object.entries(manifest.characters)) {
    const clips = Object.entries(c.clips)
      .map(([name, m]) => name + (m.speedMps ? `(${m.speedMps}m/s)` : '') + (m.loop === false ? '(once)' : ''))
      .join(', ');
    const slots = Object.keys(c.bones ?? {});
    const isMannequin = c.file.startsWith('builtin:mannequin');
    lines.push(
      `• ${id}${c.heightM ? ` — height ${c.heightM}m` : ''}: ${isMannequin ? 'POSEABLE (pose field, no clips)' : clips}` +
        (slots.length ? ` | attach slots: ${slots.join(', ')}` : '') +
        (c.morphs?.length ? ` | expressions: ${c.morphs.join(', ')}` : ''),
    );
  }
  lines.push(
    `Mannequin pose presets: ${Object.keys(POSE_PRESETS).join(', ')}. ` +
      `Joints (for pose overrides, degrees [pitch, yaw, roll]): ${MANNEQUIN_JOINTS.join(', ')}.`,
  );
  lines.push('Environments: ' + Object.keys(manifest.environments).join(', '));
  lines.push('Lighting: ' + Object.keys(manifest.lighting).join(', '));
  lines.push('Modeling: objects support rotationX/Y/Z (degrees, XYZ Euler, animatable), per-axis scale, parentId for nested groups. Prop material: roughness/metalness/opacity 0..1, emissive #RRGGBB, emissiveIntensity 0..100. prop/tube: path [[x,y,z],…] (2..64 points), radius meters (default .05), closed boolean; use for cables, rails, handles. prop/extrude additionally supports holes: arrays of closed XY outlines and bevel 0..1 meters (keep smaller than the outline features). Profiles, paths and material values remain editable.');
  lines.push('Animation: each object/group accepts visible:boolean|[{t,v:boolean}] (step), opacity:number|[{t,v,ease?}] (0..1 multiplier), animation:{timeOffset?,channels?}. Channels position.x/y/z, rotationX/Y/Z, scale.x/y/z, visible, opacity override base fields; channel value is number, [{t,v,ease?}] or {curveId,timeOffset?,timeScale?,valueScale?,valueOffset?}. Base scale stays positive/constant; animated scale channels allow zero. spec.curves:{id:{name?,mode?:continuous|step,keys:[{t,v,ease?}]}} has no fixed curve/key count limit. sceneEdit {type:"curve.create"|"curve.update",id,curve} creates/replaces a definition and validates all bindings; {type:"curve.remove",id} refuses live references. Returns curveIds and affected changedIds. query kind:sceneCurves with assetId returns id/name/mode/keyCount/objectCount; opt into curve for keys.');
  lines.push('Curve sampling: localTime=(sceneTime-object.animation.timeOffset-binding.timeOffset)*binding.timeScale; value=sample(curve,localTime)*valueScale+valueOffset. Offsets default 0, scales default 1; timeScale must be positive. Finite keys have strictly increasing nonnegative times; values hold outside the key range. Easing is on the arriving key; omitted easing is linear. Visibility channels use numeric 0/1 step keys, without easing; references require mode:step and no value transforms. Scale endpoints must be nonnegative, opacity endpoints 0..1; easing overshoot clamps to these ranges. A zero scale/opacity or hidden ancestor excludes geometry from drawing, picking and automatic framing. Explicit focus by ID still frames hidden geometry; sceneInspect includes visible and inherited opacity multiplier (excludes base material), quaternion:null at zero scale.');
  lines.push('Object animation delays apply to its transform/visibility/opacity, including legacy position/rotation keys. Each child has its own clock; parents affect resulting transforms, opacity and visibility. Delays do not shift character actions/pose/morph, camera, light-intensity or physics tracks. Group opacity also multiplies descendant light intensity; lights use intensity keys instead of direct opacity. Physics props allow visibility/opacity but keep their collider while hidden; transform channels and delayed legacy physics transform keys are rejected. Fades use ordinary transparent-object sorting and disable opaque shadows while fading. Static GLB export includes only visible geometry with sampled scale/alpha, never animation tracks.');
  lines.push('Compose shared animation with ordinary edits: add/duplicate/duplicateMany preserve curveId bindings; update animation.timeOffset for staggered copies. transform/layout/sceneArrange shift binding valueOffset or multiply its values while retaining references. Absolute scale edits at sampled zero require direct key/binding edits. Use one sceneEdit for an atomic curve-plus-binding change. Instance/group animation-only edits reuse renderers; shared curve registry changes rebuild. Director Animation properties edit channel keys, curve bindings, shared keys and object delay.');
  lines.push('Anchors: every authored object/group accepts anchors:{anchorId:{name?,position:[x,y,z],normal?,tangent?}} in object-local coordinates before transforms. normal defaults +Y, tangent defaults +X (or +Z when parallel). Vectors must be nonzero and independent. sceneEdit {type:"anchor.set",id,anchorId,anchor} upserts one definition; {type:"anchor.remove",id,anchorId} removes it. Copying keeps local anchors; anchor-only edits reuse renderers. The Director Anchors properties panel edits the same registry.');
  lines.push('Spatial primitives: sceneSpatial({assetId,timeS?,expectedRevision?,queries:[...]}) returns {ok,assetId,revision,timeS,results} for one captured scene/time, without document writes, a WebGL renderer, or a full spec reply. MCP velocut_scene_spatial; capabilities name:sceneSpatial has the input schema. Query shapes: {type:"bindings",ids?}; {type:"anchors",objectId,anchorIds?,status?:valid|invalid}; {type:"anchorRepair",objectId,anchorId,method:"face"|"raycast",ray?:{origin,direction,maxDistance?,includeHidden?}}; {type:"raycast",origin:[x,y,z],direction:[x,y,z],objectIds?,maxDistance?,includeHidden?}; {type:"surface",objectId,meshPath?:[],triangleIndex,barycentric:[a,b,c]}; {type:"distance",from,to}; {type:"angle",a,vertex,b}. A point is {position:[x,y,z],objectId?} (world without objectId, local with it) or {objectId,anchorId}. Distance is in meters, angle 0..180 degrees at vertex; zero-length angle arms fail.');
  lines.push('Spatial results: anchors returns items with world position, normal, tangent and bitangent=normal cross tangent. Raycast returns the nearest hit (or null), scoped IDs include descendants; hidden objects are excluded unless includeHidden:true. It tests geometry from both sides, independently of material face culling/texture alpha. Hit/surface includes objectId, meshPath (child indices from that object root), triangleIndex, vertexIndices, barycentric, interpolated UV, world frame and local anchor definition. Surface uses posed triangle vertices, including skin/morph deformation; weights must be 0..1 summing to 1. Reuse a handle with expectedRevision from its result; paths/triangle indices are not durable after topology changes. Collapsed frames have frameValid:false and null directions; local:null means no invertible object frame. Local anchors follow object transforms/animation, not subsequent mesh deformation; resample and anchor.set to move them. Queries are read-only; persistent surface anchors and bindings below opt into dependency updates. They are not contact/collision checks.');
  lines.push('Live surface anchors: raycast/surface results include surfaceAnchor:{kind:"surface",surface:{meshPath,triangleIndex,barycentric,sourceKey,topologyKey}} ready for anchor.set. Choose this instead of local to follow vertex/skin/morph deformation. Optional surfaceAnchor.tangent is an object-local heading projected onto the current surface (e.g. [0,0,1] for consistent roof-row headings); absent means triangle-edge tangent. References include whole topology, native geometryKey and ordered vertexIndices; never invent or overwrite these proof fields. Verified geometry.patch operations advance whole-mesh proofs while retaining each face witness: unrelated faces stay valid, changed ordered faces invalidate their own anchors. Full geometry.update, raw native replacement/reindexing and imported-source replacement remain strict. Legacy references are upgraded only when a known patch verifies their topology; do not blindly update old hashes. Invalid anchors return position:null. Measurements reject invalid anchors and failed binding dependencies. Local anchors remain fixed local points and cannot certify contact.');
  lines.push('Repair primitives: sceneSpatial query {type:"anchorRepair",objectId,anchorId,method:"face"} previews an existing surface anchor. With verified source/geometry/topology it can remap barycentric weights to the same three vertex IDs after face-order changes; it cannot guess a different face or vertex identity. It also upgrades currently-valid legacy references. method:"raycast" requires explicit ray:{origin,direction,maxDistance?,includeHidden?}; the hit must remain on the same mesh owner. Result status:candidate includes candidate.anchor, position/normal/tangent, windingReversed, orientationChanged and candidate.edit; unavailable returns a reason and no edit. Changed or unknown orientation needs review. Queries never commit.');
  lines.push('Commit a repair with sceneEdit({assetId,expectedRevision:preview.revision,edits:[candidate.edit,...],includeSpec:false}). candidate.edit is {type:"anchor.rebind",id,anchorId,expected:oldSurfaceReference,surface:newSurfaceReference}. This compares the old reference and replaces only surface, retaining current name/tangent, binding IDs, offsets and animations. Runtime requires expectedRevision and validates all final references before one undoable commit, including preflight. Stale or invalid candidates reject the whole batch. Existing 500-edit batch limit applies. Director Anchors offers paginated face-repair previews and explicit selection; orientation-changing candidates are not preselected. Use explicit ray queries for unavailable candidates.');
  lines.push('Persistent one-way bindings: spec.bindings:{bindingId:definition}; sceneEdit {type:"binding.create"|"binding.update",id,binding} creates/replaces; {type:"binding.remove",id} removes. Common definition {type:"position"|"orientation",source:{objectId,anchorId},target:{objectId,anchorId},name?,enabled?,motion?:{referenceTimeS}}. Targets must use LOCAL anchors on non-physics props, lights or groups without characters. Sources can use local/live surface anchors, including animated imported models. Position adds offset?:[x,y,z] in offsetSpace?:world|source (default world); source axes are tangent, bitangent, normal, in meters. Orientation aligns anchor normal/tangent, twist?:degrees around source normal. One active writer per type/target; dependency cycles (including parenting) are rejected atomically. No configured binding-count limit.');
  lines.push('Binding motion and edits: bindings own derived position/orientation without rewriting stored transforms or curves. Existing animation on an owned field requires explicit motion.referenceTimeS (within scene duration). Position adds authored parent-local position(t)-position(referenceTimeS); orientation postmultiplies inverse(authoredRotation(referenceTimeS))*authoredRotation(t). Scale/visibility/opacity remain authored. Position solves after orientation so the target anchor remains the pivot. sceneEdit direct position/rotation/transform/layout writes to controlled fields fail; edit binding offset/twist, edit motion channels/curves, or disable/remove first. Disabling restores the authored pose. Assembly regeneration retains controlled base transforms. Duplicates clone target bindings and remap internal sources, keeping external sources; copies.bindingIdMap names new binding IDs. Transforming a copied bound root requires detaching/editing its cloned binding. cascade remove clears bindings referencing removed objects.');
  lines.push('Binding inspection: query kind:sceneBindings returns paginated id/name/type/source/target/enabled; opt into binding for the definition. sceneEdit returns bindingIds and includes affected driven IDs in changedIds. sceneSpatial query {type:"bindings",ids?} returns valid/disabled/invalid/suspended at timeS; sceneInspect includes target binding statuses and bindingValid. Zero-scale frames suspend orientation; failures restore the deterministic authored pose for Director inspection and block downstream dependencies. Director shows anchor kind/validity, invalid-binding warnings and editable Bindings definitions. Shot rendering/capture and static GLB export reject visible failed bindings in their export scope; hidden collapsed objects may be omitted. Rebinding the source anchor restores dependents automatically.');
  lines.push('Assemblies via sceneEdit type:assembly: table/chair/stairs with width/depth/height/thickness (meters), steps for stairs. Parts are ordinary editable props under a group. Regeneration merges old recipe/current edits/new recipe: values matching old generated defaults follow new parameters; differing values (per-axis for transforms), shared materials, animation, anchors and other custom fields survive. Deleted parts stay deleted while present in the old recipe. This value-based merge does not store explicit override provenance; a value equal to the old default follows the recipe. sceneArrange provides bounding-box ground/on/align/distribute placement.');
  lines.push('Batch authoring through sceneEdit({assetId,expectedRevision?,edits,dryRun?}): duplicateMany {type:"duplicateMany",ids,copies:[{prefix,transform?,relative?}],timeS?} clones each selected subtree into prefix/oldId, remaps internal references, returns copies:[{prefix,rootIds,idMap}] and createdIds. Optional transform applies to each copied root; relative:true preserves separation with offsets. Originals remain. transform {type:"transform",ids,transform:{position?:{x?,y?,z?},rotation?:{x?,y?,z?},scale?:number|{x?,y?,z?}},relative?,timeS?} sets supplied local components at timeS (default 0), retaining omitted axes and shifting animation keys; relative adds position/Euler degrees, multiplies positive scales about individual origins. Physics props require timeS:0. Reject parent/descendant overlap.');
  lines.push('layout {type:"layout",ids,timeS?,layout:...} places object origins in ID order in a shared parent/bone frame. Layout options: {mode:"line",origin:{x?,y?,z?},step:{x?,y?,z?}}; {mode:"grid",origin:{x?,y?,z?},columns,spacing:{x,z}} (row-major X/Z); {mode:"radial",center:{x?,y?,z?},radius,startAngle?,sweepAngle?,facing?:"keep"|"inward"|"outward"|"tangent",rotationOffset?}. Omitted origin/center axes are zero. Radial: angle 0=+Z, positive toward +X; default sweep 360 omits repeated endpoint, shorter arcs include endpoints; facing controls local +Z yaw plus rotationOffset. Combine duplicateMany + layout + transform in ONE sceneEdit for one atomic undo step.');
  lines.push('sceneArrange mode:"distribute" packs world bounds in ids order along axis (default x), with gap meters between edges and optional start for first lower bound; default start keeps first lower edge, other world coordinates remain. Different parents supported. No referenceId. sceneEdit/sceneArrange dryRun:true compiles a candidate without changing document/history: {ok:true,preview:true,ready:false,revision,spec,...}; commit same options without dryRun using returned revision. Preview returns no image. Separate script calls are separate transactions. Limits: 200 ordinary props (assembly parts count), no fixed shared-instance count limit, 100 groups, 8 characters, 16 lights, no fixed spec byte limit, 100 copy requests/500 generated objects per duplicateMany.');
  lines.push('Explicit meshes: prop/mesh has vertices [[x,y,z],…] (3..4096), faces [[a,b,c],…] (1..8192 counter-clockwise index triples), optional uvs [[u,v],…] per vertex. All geometry is editable data; the document spec has no fixed byte limit.');
  lines.push('Shared geometry: SceneSpec.geometries accepts inline geometry in a scene-local registry {geometryId:{name?,vertices,faces,uvs?}}. sceneEdit operations: {type:"geometry.create",id,geometry}, {type:"geometry.update",id,geometry} (replace the whole definition, updates all linked instances), {type:"geometry.remove",id} (reject while referenced). Add instances with {type:"add",kind:"prop",object:{id,model:"prop/instance",geometryId,position?,rotationX/Y/Z?,scale?,parentId?,color?,material?}}. Ordinary update/transform/layout/duplicate/remove work on each instance; duplicate keeps the shared reference. {type:"geometry.clone",id,newId} clones a geometry definition, reusing immutable file bytes until changed. {type:"makeUnique",id,geometryId?} creates a new geometry definition and converts one instance into a resource-backed prop/mesh, preserving object ID/transform/material and counting against the 200 ordinary-prop limit; no vertices are put back into the manifest. geometryId is the optional new registry key (otherwise unique_N). It does not delete the shared resource. Physics/bone attachment require makeUnique. Opaque instances batch; partially transparent instances use individual draws with shared geometry, and return to batches at alpha 1. Instances remain independently pickable/editable.');
  lines.push('Budget and bulk editing: query({kind:"sceneBudget",assetId}) returns current counts/limits; query kind:sceneGeometries returns paginated geometry summaries (opt into fields:["id","geometry"] only for legacy inline vertices; sceneGeometry reads resource-backed arrays); query kind:sceneObjects includes model, geometryId and materialId. sceneEdit({assetId,edits,expectedRevision,preflight:true}) checks structure and budgets without compiling/rendering, writing files or committing; patches may read their source resource; ready:false,compiled:false. A valid preflight is not proof of rendered quality. dryRun:true additionally compiles. includeSpec:false suppresses full specs in edit replies. Send at most 500 edits per batch; each committed batch is one undo step. Limits: ' + JSON.stringify(SCENE_LIMITS) + '. A null limit means no configured ceiling for that metric. Exceeding a limit is a failed edit, never silently merge/simplify user-requested parts. The runtime persists inline geometry as immutable project files in spec.geometryResources; scene references/history contain metadata only. The manifest has no fixed byte limit (specBytes:null); geometryBytes has a separate budget. used.specBytes is the projected compact size, documentBytes is the current JSON size. Instance/group transform-only edits return updateMode:transforms and retain renderers; other edits return rebuild. Old inline specs remain readable.');
  lines.push('Geometry editing: sceneGeometry({assetId,geometryId,attribute?:vertices|faces|uvs,offset?,limit?:1..1024}) reads a page with revision/resource/total/items/nextOffset. MCP tool: velocut_scene_geometry. query sceneGeometries includes storage:inline|resource; opt into resource for source metadata, geometry only exists for legacy inline entries. sceneEdit {type:"geometry.patch",id,attribute:"vertices"|"faces"|"uvs",updates:[{index,value}]} replaces 1..1024 existing unique indices, preserving other data. Topology insertions/removals still use full geometry.update. Every edit creates an immutable geometry version as needed; undo restores old references. dryRun saves no geometry files: commit the original edits, not the returned temporary spec.');
  lines.push('Shared materials: spec.materials is a registry (max 128) with definitions {name?,color?:#RRGGBB,roughness?,metalness?,opacity?,emissive?,emissiveIntensity?,side?}. sceneEdit {type:"material.create"|"material.update",id,material} creates/replaces a definition; {type:"material.remove",id} refuses live references. Props bind materialId; prop.color and supplied prop.material fields override shared values. Clear local color/material to inherit again. Query sceneMaterials for id/name/objectCount, request field material for the definition. Resource-backed prop/mesh supports geometryId and can use transparency/physics/bone attachment through existing APIs; instances support opacity too (individual draws during transparency). geometry.clone + update binding + geometry.patch can compose in one sceneEdit. Material/geometry IDs are returned separately in materialIds/geometryIds.');
  lines.push('Independent lights: add kind:light objects with id, type point/spot/directional/ambient, color, intensity (constant or keyframed), transform/parentId. Point/spot: distance (0=infinite), decay. Spot: angle (half-angle degrees <90), penumbra 0..1. shadow boolean. Directional/spot aim down local -Z; rotate to aim. lighting:none disables preset rigs. Imported self-contained GLBs are registered by sceneImportModel; sceneInspect.spec.models contains their exact animation names.');
  lines.push('Props: ' + Object.keys(manifest.props).join(', '));
  lines.push(
    'Pace walks so position keyframes match the gait: distance = speedMps × seconds ' +
      '(e.g. Walking at 1.4m/s covers 4.2m in 3s). World units are meters, ground is y=0, camera looks -Z by default.',
  );
  lines.push(
    'Physics (per-prop opt-in, baked deterministically): physics: "dynamic" | "fixed" | "kinematic" | ' +
      '{type, mass?, restitution?, friction?, velocity?, angularVelocity?, startAt?, colliders?}. ' +
      'Reach for it when motion should EMERGE (falls, collapses, impacts, rolling, scattering); ' +
      'keep keyframes for choreographed moves. Characters are not simulated.',
  );
  lines.push('Collision shapes: physics.colliders:{colliderId:definition} puts all parts on ONE rigid body. Omit for implicit default:{shape:"auto"}; {} disables collision. Automatic primitives stay analytic, other fixed/kinematic objects use triangle meshes preserving holes, dynamic objects use a convex hull (fills cavities). Definitions: {shape:"auto",name?}; {shape:"box",halfExtents:[x,y,z],position?,rotation?,name?}; {shape:"sphere",radius,position?,rotation?,name?}; {shape:"mesh"|"convexHull",geometryId?,position?,rotation?,name?}. Positions and sizes are object-local meters before object scale, rotation is XYZ degrees. Omit geometryId to use the visual mesh. Dynamic triangle meshes are rejected; compose convex parts instead. Explicit spheres require uniform scale. Body mass is distributed across parts by volume; an empty dynamic body defaults to 1 kg.');
  lines.push('Collider primitives: sceneEdit {type:"collider.create"|"collider.update",id:objectId,colliderId,collider}, {type:"collider.remove",id,colliderId}, {type:"collider.reset",id}. Physics must already be enabled. First edits materialize the implicit default, so remove default in the same batch when composing replacement parts. reset restores automatic selection. Queries in sceneSpatial: {type:"colliders",objectIds?,offset?,limit?} returns actual shapes/counts/masses/warnings plus body summaries; {type:"colliderGeometry",objectId,colliderId,space?:"local"|"world",offset?,limit?} returns paged actual Rapier line segments [ax,ay,az,bx,by,bz]. Local lines already include object scale. Paging defaults to 256, max 1024 per response, not a scene-capacity limit. directorSession({colliderView:"off"|"selected"|"all"}) toggles workspace wireframes, hidden in shot view. Geometry raycasts still measure visible geometry; collider boundaries do not certify solid containment or structural safety.');
  return lines.join('\n');
}
