import {ProviderError,type ProviderDefinition,type JsonObject,type ProviderContext,type ProviderCall} from '@velocut/provider-sdk';
import {validateVideoModel,type ModelSettings} from '@velocut/provider-sdk/catalog';
function base(config:Readonly<JsonObject>){if(typeof config.baseUrl!=='string')throw Error('Base URL is required');const u=new URL(config.baseUrl);if(!['https:','http:'].includes(u.protocol)||u.username||u.password||u.search||u.hash)throw Error('Use an HTTP(S) Base URL without credentials, query or fragment');return config.baseUrl.replace(/\/+$/,'');}
const route=(base:string,path:string)=>base+(base.endsWith('/v1')?path.replace(/^\/v1/,''):path);
function client(context:ProviderContext){const url=base(context.config);return async(path:string,call:ProviderCall,body?:JsonObject)=>{
 const token=await context.credentials.get('apiKey');call.signal?.throwIfAborted();const response=await context.fetch(route(url,path),{method:body?'POST':'GET',headers:{'content-type':'application/json',authorization:`Bearer ${token}`},...(body?{body:JSON.stringify(body)}:{}),signal:call.signal});const data=await response.json().catch(()=>({})) as any;
 if(!response.ok||data.base_resp?.status_code)throw new ProviderError({phase:body?'submit':'poll',code:String(data.base_resp?.status_code??'MINIMAX_HTTP'),message:data.base_resp?.status_msg??`MiniMax HTTP ${response.status}`,httpStatus:response.status,outcome:response.status>=500?'unknown':'rejected',retryable:response.status>=500||response.status===429});return data;
};}
export const minimaxVideoProvider:ProviderDefinition={apiVersion:1,id:'minimax-video',label:'MiniMax Video API',capabilities:['video.generate'],credentials:[{name:'apiKey',required:true}],configSchema:{type:'object',required:['baseUrl'],properties:{baseUrl:{type:'string'},modelSettings:{type:'object'}}},create(context){
 const json=client(context),settings=context.config.modelSettings as unknown as ModelSettings|undefined;
 return {models:()=>[],supports:request=>{try{if(request.capability!=='video.generate'||typeof request.input.prompt!=='string'||!request.input.prompt.trim())throw Error('Video prompt is required');if(Object.keys(request.input).some(k=>!['prompt','durationS','resolution','parameters','firstFrameReferenceId','generateAudio'].includes(k)))throw Error('MiniMax Video API does not accept this input');if(request.input.generateAudio===true)throw Error('This video protocol has no generated audio option');validateVideoModel(settings,request.input);return {supported:true};}catch(e){return {supported:false,reason:String(e instanceof Error?e.message:e)};}},
 async submit(request,call){const i=request.input,params=i.parameters as JsonObject??{},body:JsonObject={model:request.model,prompt:i.prompt,...params};for(const [from,to] of [['durationS','duration'],['resolution','resolution']])if(i[from]!==undefined)body[to]=i[from];
 if(i.firstFrameReferenceId){if(!call.resources)throw Error('Reference transport is required');body.first_frame_image=await call.resources.urlFor(String(i.firstFrameReferenceId),'image');}
 const result=await json('/v1/video_generation',call,body);return {id:result.task_id};},
 async poll(receipt,call){const data=await json(`/v1/query/video_generation?task_id=${encodeURIComponent(receipt.id)}`,call);if(data.status==='Success'){if(!data.file_id)throw Error('Completed task has no file ID');return {state:'ready',receipt:{...receipt,state:{fileId:String(data.file_id)}}};}if(['Fail','Failed','Cancelled'].includes(data.status))return {state:'failed',error:{phase:'poll',code:'MINIMAX_VIDEO_FAILED',message:data.base_resp?.status_msg??'Video generation failed',outcome:'rejected',retryable:false}};if(!['Preparing','Queueing','Processing'].includes(data.status))throw new ProviderError({phase:'poll',code:'UNKNOWN_STATUS',message:'Unknown MiniMax video status',outcome:'unknown',retryable:false});return {state:'running',status:data.status};},
 async collect(receipt,call){if(typeof receipt.state?.fileId!=='string')throw Error('Missing video file receipt');const data=await json(`/v1/files/retrieve?file_id=${encodeURIComponent(receipt.state.fileId)}`,call);if(typeof data.file?.download_url!=='string')throw Error('Missing video download URL');return {outputs:[{kind:'video',source:{kind:'url',url:data.file.download_url}}]};},
 };
}};
export const minimaxMusicProvider:ProviderDefinition={apiVersion:1,id:'minimax-music',label:'MiniMax Music API',capabilities:['audio.generate'],credentials:[{name:'apiKey',required:true}],configSchema:{type:'object',required:['baseUrl'],properties:{baseUrl:{type:'string'}}},create(context){
 const json=client(context);return {models:()=>[],supports:r=>r.capability==='audio.generate'&&typeof r.input.lyrics==='string'&&r.input.lyrics.trim().length>0&&Object.keys(r.input).every(k=>['prompt','lyrics','sampleRate','bitrate','watermark'].includes(k))?{supported:true}:{supported:false,reason:'Song lyrics are required and only documented music parameters are accepted'},async execute(request,call){const i=request.input,body:JsonObject={model:request.model,prompt:i.prompt??'',lyrics:i.lyrics,stream:false,output_format:'hex',audio_setting:{format:'mp3',sample_rate:i.sampleRate??44100,bitrate:i.bitrate??256000},...(i.watermark!==undefined?{aigc_watermark:i.watermark}:{})};const data=await json('/v1/music_generation',call,body),hex=data.data?.audio;if(typeof hex!=='string'||!hex.length||hex.length%2||!/^[\da-f]+$/i.test(hex))throw Error('Music API returned invalid audio');const bytes=new Uint8Array(hex.length/2);for(let n=0;n<bytes.length;n++)bytes[n]=parseInt(hex.slice(n*2,n*2+2),16);return {outputs:[{kind:'audio',mimeType:'audio/mpeg',source:{kind:'bytes',bytes}}]};}};
}};
